BEGIN;
--
-- Add field followers to myuser
--
CREATE TABLE "accounts_myuser_followers" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "from_myuser_id" bigint NOT NULL, "to_myuser_id" bigint NOT NULL);
ALTER TABLE "accounts_myuser_followers" ADD CONSTRAINT "accounts_myuser_follower_from_myuser_id_to_myuser_c8d374cc_uniq" UNIQUE ("from_myuser_id", "to_myuser_id");
ALTER TABLE "accounts_myuser_followers" ADD CONSTRAINT "accounts_myuser_foll_from_myuser_id_c2dc27a3_fk_accounts_" FOREIGN KEY ("from_myuser_id") REFERENCES "accounts_myuser" ("pkid") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_myuser_followers" ADD CONSTRAINT "accounts_myuser_foll_to_myuser_id_33f3f09f_fk_accounts_" FOREIGN KEY ("to_myuser_id") REFERENCES "accounts_myuser" ("pkid") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_myuser_followers_from_myuser_id_c2dc27a3" ON "accounts_myuser_followers" ("from_myuser_id");
CREATE INDEX "accounts_myuser_followers_to_myuser_id_33f3f09f" ON "accounts_myuser_followers" ("to_myuser_id");
COMMIT;
