version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes: # persist data and share file between multiple container in host machine
      - .:/app:z # map the file in host to container
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.rabbitmq
    # FIXME: Using 3rd provider postgres db
    depends_on:
      - postgres
      # - mailhog
    command: /start.sh
    networks:
      - instagram-api

  # FIXME: Using 3rd provider postgres db
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data # This is the default path to postgres data storage
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - instagram-api

  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - static_volume:/app/mediafiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - instagram-api

  rabbitmq_server:
    hostname: rabbitmq
    build:
      context: .
      dockerfile: ./docker/local/rabbitmq/Dockerfile
    ports:
      # OPTIONAL: Expose the GUI port
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    env_file:
      - ./.envs/.local/.rabbitmq
    command: /start.sh
    networks:
      - instagram-api

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.rabbitmq
    depends_on:
      - rabbitmq_server
      - postgres
    networks:
      - instagram-api

  flower:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-flower.sh
    volumes:
      - flower_data:/data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.rabbitmq
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq_server
      - postgres
      - celery_worker
    networks:
      - instagram-api

networks:
  instagram-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  # FIXME: Using 3rd Provider postgres db
  local_postgres_data: {}
  local_postgres_data_backups: {}
  flower_data: {}
