version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes: # persist data and share file between multiple container in host machine
      - .:/app:z # map the file in host to container
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.cassandra
    # FIXME: Using 3rd provider postgres db
    depends_on:
      - postgres
      # - mailhog
    command:  /bin/bash -c "ls -la && /start.sh"
    networks:
      - instagram-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data # This is the default path to postgres data storage
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - instagram-api

  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - static_volume:/app/mediafiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - instagram-api

  rabbitmq_server:
    hostname: rabbitmq
    build:
      context: .
      dockerfile: ./docker/local/rabbitmq/Dockerfile
    ports:
      # OPTIONAL: Expose the GUI port
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    env_file:
      - ./.envs/.local/.rabbitmq
    command: /start.sh
    networks:
      - instagram-api

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.cassandra
    depends_on:
      - rabbitmq_server
      - postgres
    networks:
      - instagram-api

  # CASSANDRA
  cassandra:
    image: cassandra:latest
    volumes:
      - local_cassandra_data:/var/lib/cassandra/data
    ports:
      - "9042:9042"
    expose:
      - "9042"
    networks:
      - instagram-api
  
  cassandra_init:
    depends_on:
      - cassandra
    build:
      context: .
      dockerfile: ./docker/local/cassandra/Dockerfile
    env_file:
      - ./.envs/.local/.cassandra
    command: cqlsh cassandra -f /schema.cql
    networks:
      - instagram-api
    

networks:
  instagram-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_cassandra_data: {}