# Generated by Django 4.2.5 on 2023-09-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStory",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("media_url", models.URLField()),
                ("live_time", models.PositiveSmallIntegerField(default=86400)),
                ("expired", models.BooleanField(default=False)),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "Min"),
                            (10, "Medium"),
                            (15, "Long"),
                            (30, "Extralong"),
                        ],
                        default=10,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("VIDEO", "Video"), ("IMAGE", "Image")],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "privacy_mode",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("PUBLIC", "Public"),
                            ("FRIEND_ONLY", "Friend only"),
                        ],
                        default="FRIEND_ONLY",
                        max_length=20,
                    ),
                ),
                (
                    "excluded_users",
                    models.ManyToManyField(
                        related_name="excluded_stories", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story",
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_views",
                        to="stories.userstory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_viewer",
                "unique_together": {("user", "story")},
            },
        ),
    ]
