# Generated by Django 4.2.5 on 2023-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="media_url",
            field=models.URLField(max_length=2000),
        ),
    ]
