# Generated by Django 4.2.5 on 2023-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0004_userstory_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="live_time",
            field=models.PositiveSmallIntegerField(
                choices=[(4300, "Halfday"), (8600, "Oneday"), (17200, "Twoday")],
                default=8600,
            ),
        ),
    ]
