# Generated by Django 4.2.5 on 2023-10-12 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0005_alter_userstory_live_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storyview",
            options={"ordering": ["-viewed_at"]},
        ),
        migrations.AlterModelOptions(
            name="userstory",
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
    ]
