# Generated by Django 4.2.5 on 2024-01-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0006_alter_room_description"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("series_name", models.CharField(max_length=255)),
                ("gpu", models.CharField(max_length=255)),
                ("gpu_max_fre", models.CharField(max_length=50)),
                ("cpu", models.CharField(max_length=255)),
                ("cpu_max_fre", models.CharField(max_length=50)),
                ("vision_acceleration", models.CharField(max_length=255)),
                ("storage", models.CharField(max_length=255)),
                ("memory", models.CharField(max_length=255)),
                ("power", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "device_spec",
            },
        ),
        migrations.RemoveField(
            model_name="device",
            name="firmware_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="gpu_model",
        ),
        migrations.AddField(
            model_name="device",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="house.room",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="secret",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("STAND_BY", "Stand By"),
                    ("ERROR", "Error"),
                    ("OFFLINE", "Offline"),
                ],
                default="OFFLINE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="specification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="device.devicespec",
            ),
        ),
    ]
