# Generated by Django 4.2.5 on 2024-01-29 15:34

from django.db import migrations


def create_default_device_spec(apps, schema_editor):
    DeviceSpec = apps.get_model(
        "device", "DeviceSpec"
    )  # Replace 'your_app_name'

    existed = DeviceSpec.objects.filter(
        name="Jetson Xavier", series_name="X Series"
    ).exists()
    # Check if default device already exists
    if not existed:
        DeviceSpec.objects.create(
            name="Jetson Xavier",
            series_name="X Series",
            gpu="NVIDIA GeForce RTX 3080",
            gpu_max_fre="1710 MHz",
            cpu="AMD Ryzen 9 5900X",
            cpu_max_fre="4.8 GHz",
            vision_acceleration="Tensor Cores",
            storage="1 TB SSD",
            memory="32 GB DDR4",
            power="750W",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_alter_devicespec_unique_together"),
    ]

    operations = [
        migrations.RunPython(create_default_device_spec),
    ]
