# Generated by Django 4.2.5 on 2024-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_insert_default_device_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicespec",
            name="image",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
    ]
