# Generated by Django 4.2.5 on 2023-10-01 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="followers",
            field=models.ManyToManyField(
                related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
