# Generated by Django 4.2.5 on 2023-12-10 15:54

import core_apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_myuser_is_test"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("objects", core_apps.accounts.managers.UserManager()),
                ("tests", core_apps.accounts.managers.TestUserManager()),
            ],
        ),
    ]
