# Generated by Django 4.2.5 on 2023-12-17 04:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_myuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="Ho Chi Minh", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="VN", max_length=2
            ),
        ),
    ]
