# Generated by Django 4.2.5 on 2023-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile__nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="_nickname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunSQL(
            "UPDATE profile SET _nickname=NULL WHERE _nickname='';",
        ),
        migrations.AlterField(
            model_name="profile",
            name="_nickname",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(default=""),
        ),
    ]
