# Generated by Django 4.2.5 on 2023-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                related_name="followings", to="profiles.profile"
            ),
        ),
    ]
