BEGIN;
--
-- Create model UserStory
--
CREATE TABLE "story" ("pkid" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "id" uuid NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "media_url" varchar(200) NOT NULL, "live_time" smallint NOT NULL CHECK ("live_time" >= 0), "expired" boolean NOT NULL, "duration" smallint NOT NULL CHECK ("duration" >= 0), "media_type" varchar(20) NOT NULL, "privacy_mode" varchar(20) NOT NULL, "user_id" bigint NOT NULL);
CREATE TABLE "story_excluded_users" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "userstory_id" bigint NOT NULL, "myuser_id" bigint NOT NULL);
--
-- Create model StoryView
--
CREATE TABLE "story_viewer" ("pkid" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "viewed_at" timestamp with time zone NOT NULL, "story_id" bigint NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "story" ADD CONSTRAINT "story_user_id_84537394_fk_accounts_myuser_pkid" FOREIGN KEY ("user_id") REFERENCES "accounts_myuser" ("pkid") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "story_user_id_84537394" ON "story" ("user_id");

ALTER TABLE "story_excluded_users" ADD CONSTRAINT "story_excluded_users_userstory_id_myuser_id_79b3a596_uniq" UNIQUE ("userstory_id", "myuser_id");
ALTER TABLE "story_excluded_users" ADD CONSTRAINT "story_excluded_users_userstory_id_aad3f96b_fk_story_pkid" FOREIGN KEY ("userstory_id") REFERENCES "story" ("pkid") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "story_excluded_users" ADD CONSTRAINT "story_excluded_users_myuser_id_9557aef3_fk_accounts_myuser_pkid" FOREIGN KEY ("myuser_id") REFERENCES "accounts_myuser" ("pkid") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "story_excluded_users_userstory_id_aad3f96b" ON "story_excluded_users" ("userstory_id");
CREATE INDEX "story_excluded_users_myuser_id_9557aef3" ON "story_excluded_users" ("myuser_id");

ALTER TABLE "story_viewer" ADD CONSTRAINT "story_viewer_user_id_story_id_dacd070c_uniq" UNIQUE ("user_id", "story_id");
ALTER TABLE "story_viewer" ADD CONSTRAINT "story_viewer_story_id_c9e41837_fk_story_pkid" FOREIGN KEY ("story_id") REFERENCES "story" ("pkid") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "story_viewer" ADD CONSTRAINT "story_viewer_user_id_c638e34b_fk_accounts_myuser_pkid" FOREIGN KEY ("user_id") REFERENCES "accounts_myuser" ("pkid") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "story_viewer_story_id_c9e41837" ON "story_viewer" ("story_id");
CREATE INDEX "story_viewer_user_id_c638e34b" ON "story_viewer" ("user_id");
COMMIT;
