# Generated by Django 4.2.5 on 2024-01-25 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="phone",
        ),
    ]
