# Generated by Django 4.2.5 on 2024-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_remove_house_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
