# Generated by Django 4.2.5 on 2024-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_alter_house_address_alter_house_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="owner",
            new_name="owners",
        ),
    ]
