# Generated by Django 4.2.5 on 2024-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_rename_owner_house_owners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
