# Generated by Django 4.2.5 on 2024-01-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_alter_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
