# Generated by Django 4.2.5 on 2024-02-02 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("house", "0006_alter_room_description"),
        ("permission", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserPermission",
            new_name="Permission",
        ),
    ]
