# Generated by Django 4.2.5 on 2024-02-02 09:30
from django.db import migrations
from .. import enums


def add_default_permissions(apps, schema_editor):
    PermissionType = apps.get_model(
        "permission", "PermissionType"
    )  # Replace 'your_app_name'
    for permission_type in enums.PermissionTypeChoices.choices:
        permission_name = permission_type[0]
        try:
            PermissionType.objects.create(
                name=permission_name,
                description=enums.get_description(permission_name),
            )
            print("generated", permission_name, flush=True)
        except:
            print("Already generated", permission_name, flush=True)
            # Ignore if already exists
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0002_rename_userpermission_permission"),
    ]

    operations = [
        migrations.RunPython(add_default_permissions),
    ]
